# DOMINUS funding options
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: AlessioBrillo
# patreon: # Uncomment to add Patreon
# open_collective: # Uncomment to add Open Collective
# ko_fi: # Uncomment to add Ko-fi
# custom: # Uncomment to add custom sponsorship URLs
